### ISSUE TITLE
NUnit 3 has a new syntax for specifying command line arguments

### ISSUE THREAD

**Issue by abe545** [Inedo/bmx-nunit#10]
The 2.6.4 docs:
http://nunit.org/index.php?p=consoleCommandLine&r=2.6.4

The 3.0 docs:
https://github.com/nunit/nunit/wiki/Console-Command-Line

I'm guessing that the version of the runner would need to be specified in order to support both versions? Besides the change from `/` to `--`, the `/xml` switch now seems to be `--result:filename;format=nunit2` (if you support the new xml format, you can drop the `;format=nunit2`).

**Comment by kmcgain** [comment]
For anyone wanting a workaround in the meantime just create a bat file in the nunit-console folder:
```
set arg=%2
set xarg=%arg:~5%
"%~dp0\nunit3-console.exe" %1 --result:%xarg%;format=nunit2
```

Use the full path to bat file as the nunit exe and test file arg as normal.
